#! /bin/bash

FTEMP="/etc/portage/package."

print_help() {
    cat <<EOF
This is the help message for my quickly written script

Options:
    -a|--accept
        Add a proceeding string to the package.accept_keywords file
    -u|--use
        Add a proceeding string to the package.use file
    -um|--unmask
        Add a proceeding string to the package.unmask file
    -m|--mask
        Add a proceeding string to the package.mask file
    -l|--license
        Add a proceeding string to the package.license file
    -e|--edit
        Edit the selected file

Example:
    metool -a "sys-kernel/gentoo-sources ~amd64"
    metool -e -a
EOF
}

for var in $@; do
    case ${var} in
        -e|--edit)
            EDIT=true; shift
            ;;
        -a|--accept)
            FILE="${FTEMP}accept_keywords"; shift; break
            ;;
        -u|--use)
            FILE="${FTEMP}use";             shift; break
            ;;
        -um|--unmask)
            FILE="${FTEMP}unmask";          shift; break
            ;;
        -m|--mask)
            FILE="${FTEMP}mask";            shift; break
            ;;
        -l|--license)
            FILE="${FTEMP}license";         shift; break
            ;;
        -h|--help|*)
            print_help
            exit 0
            ;;
    esac
done

if [ ${EDIT} ]; then
    sudo -E ${EDITOR} ${FILE}
else
    if [[ $UID != 0 ]]; then
        echo "$@" | sudo tee -a $FILE
    else
        echo "$@" >> $FILE
    fi
fi

echo "Done"
exit 0
