#! /bin/sh

# Set proper ENV VARS
export LANG="en_GB.UTF-8"

export EDITOR="gvim"            # default editor
export PAGER="less"             # default pager

#export BROWSER="luakit"         # default browser
export BROWSER="chromium"        # default browser
export SAGE_BROWSER=$BROWSER    # default SAGE browser

export PDFVIEWER="zathura"      # default pdfviewer for texdoc

export XDG_MAILER="mutt"        # default mailer
export MAILER=$XDG_MAILER       # just make some stuff work

# Use system fonts in JAVA applications
export _JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=on'

# Add the scripts directory to the path
export PATH=$PATH:${HOME}/bin
